---

version: "3"

services:
  sonic:
    image: valeriansaliou/sonic:v1.2.3
    ports:
      - "1491:1491"
    volumes:
      - ./config.cfg:/etc/sonic.cfg:ro
      - ./data/store:/var/lib/sonic/store/

